### ISSUE TITLE
加载model报错

### ISSUE THREAD

**Issue by nuass** [bojone/bytepiece#10]
按照以下加载模型做分词测试报错。
环境：加载模型
bytepiece.id.eu.plus.80k.model
from bytepiece import Tokenizer

tokenizer = Tokenizer('bytepiece.model')
这一步报错
![fe036e740e0d4f2bba9de520d7630c1](https://github.com/bojone/bytepiece/assets/22679115/55c57103-1305-48d3-a4ef-d19a1dfe6018)
是加载编码有问题吗，看代码这里的K 是二进制编码
![6ad6e449d88238762b883a51b219d7e](https://github.com/bojone/bytepiece/assets/22679115/b4909e7a-430e-496d-8a0e-b93ffca06dcc)

**Comment by bojone** [comment]
如果我没理解错，应该是安装了unicode版本的pyahocorasick？有没有按照README安装bytes版本的pyahocorasick？

**Comment by nuass** [comment]
> 如果我没理解错，应该是安装了unicode版本的pyahocorasick？有没有按照README安装bytes版本的pyahocorasick？

是这个原因，解决啦，谢谢苏神。
`git clone git@github.com:WojciechMula/pyahocorasick.git
`
`AHOCORASICK_BYTES=1 pip install ./pyahocorasick
`
