### ISSUE TITLE
是否考虑添加断点和增量训练功能？（适配大规模语料）

### ISSUE THREAD

**Issue by baisechundu** [bojone/bytepiece#19]
感谢苏老师的开源实现，做到真正意义上的 `Byte Pair Encode`。在使用过程中，对于超大型语料（70G文本）的训练，我遇到了两个问题：
1. 进程数量过多时，内存占用还是相当可观的，占用较高的是 `n-gram` 的 `Merge` 阶段和 `Count Pieces`。一旦因为内存问题卡死后，训练就要重新开始。为了缓解内存压力，不同阶段我设置了不同的进程数，并适当降低了 `batch_size`，但训练又得重新开始。所以，苏老师是否考虑添加断点功能，支持断点续练。
2. 针对超大型语料（上百 GB 的数据量），没有硬件支持想要一次处理完几乎不可能。因此，是否考虑添加增量训练的功能，这样大的语料可以做切分，分配给多台设备训练，在某个中间阶段可以 `Merge` 多台设备生成的中间结果继续后面的操作。

期待您的回复！

**Comment by bojone** [comment]
训练阶段的内存消耗本质上是因为n大了之后n-gram的数量非常多，统计起来自然很占内存，这个根本的优化手段就只能是用C/C++这些更加底层的语言来编程实现了，但这超出了我的能力范围。至于增量训练，直觉上不会有什么本质改进，因为增量意味着你在训练之前需要把占了上百G内存的n-gram统计结果重新载入内存中，省不了多少。

如果放弃确定性的结果，引入随机训练，那么优化的思路倒是简单，每次都采样一定的样本更新统计结果，并对统计结果做一些截断就行了，sentencepiece也有类似的随机训练算法。不过考虑到其实几十G语料训练出来的tokenizer其实完全够用了，加到几百G感觉也不会有什么实质改变，所以就没往这方面走

**Comment by baisechundu** [comment]
> 训练阶段的内存消耗本质上是因为n大了之后n-gram的数量非常多，统计起来自然很占内容，这个根本的优化手段就只能是用C/C++这些更加底层的语言来编程实现了，但这超出了我的能力范围。至于增量训练，直觉上不会有什么本质改进，因为增量意味着你在训练之前需要把占了上百G内存的n-gram统计结果重新载入内存中，省不了多少。
> 
> 如果放弃确定性的结果，引入随机训练，那么优化的思路倒是简单，每次都采样一定的样本更新统计结果，并对统计结果做一些截断就行了，sentencepiece也有类似的随机训练算法。不过考虑到其实几十G语料训练出来的tokenizer其实完全够用了，加到几百G感觉也不会有什么实质改变，所以就没往这方面走

> tokenizer 的训练这块我没什么经验，以为语料越多越好。感谢苏老师的回复。
